[package]
name = "mini-nats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.24.1", features = ["full"] }
bytes = "1.3.0"
tokio-stream = "0.1"
rand = "0.8.5"
